const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const eslintPluginPrettierRecommended = require('eslint-plugin-prettier/recommended');

module.exports = defineConfig([
  expoConfig,
  eslintPluginPrettierRecommended,
  {
    ignores: [
      'dist/*',
      '.expo/*',
      'expo-env.d.ts',
      // Regenerated by the NativeWind metro plugin on every start.
      'nativewind-env.d.ts',
    ],
  },
  {
    rules: {
      // Design tokens live in src/global.css; a raw hex in a component means a
      // token is missing. Warn rather than error so prototyping isn't blocked.
      'no-restricted-syntax': [
        'warn',
        {
          selector: 'Literal[value=/^#(?:[0-9a-fA-F]{3}){1,2}$/]',
          message:
            'Hardcoded hex colour. Add a token to src/global.css and use a className instead.',
        },
      ],
    },
  },
  {
    // The one file that is *supposed* to contain hex values — it is the
    // TypeScript mirror of the CSS tokens for APIs that cannot take a class.
    files: ['src/constants/theme.ts'],
    rules: { 'no-restricted-syntax': 'off' },
  },
]);
